In [1]:
import torch
import numpy as np

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
np.array = np.array(data)
x_np = torch.from_numpy(np.array)

x_ones = torch.ones_like(x_data)
print(f"One tensor:\n{x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor :\n {x_rand}\n")

One tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor :
 tensor([[0.7834, 0.6913],
        [0.3622, 0.5139]])



In [2]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tenor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor,ones_tenor,zeros_tensor)

tensor([[0.7445, 0.6746, 0.4482],
        [0.2027, 0.1424, 0.0774]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
tensor = torch.rand(3,4)
print(f"Shape of tensor {tensor.shape}")
print(f"Datatype of tensor {tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device}")


Shape of tensor torch.Size([3, 4])
Datatype of tensor torch.float32
Device tensor is stored on:cpu


In [8]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
tensor = torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(tensor[0])
print(tensor[:,0])
print(tensor[...,-1])
tensor[:,1]=0
print(tensor)

tensor([1, 2, 3, 4])
tensor([1, 1, 1, 1])
tensor([4, 4, 4, 4])
tensor([[1, 0, 3, 4],
        [1, 0, 3, 4],
        [1, 0, 3, 4],
        [1, 0, 3, 4]])


In [10]:
import torch

# 假设 tensor 是一个形状为 (N, C) 的张量，并且数据类型为浮点型
tensor = torch.randn(2, 3).float()  # 示例初始化为 float 类型

# 使用 torch.cat 拼接张量
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print("t1:", t1)

# 矩阵乘法
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print("y1:", y1)
print("y2:", y2)

# 使用 out 参数进行矩阵乘法
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print("y3:", y3)

# 元素乘法
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print("z1:", z1)
print("z2:", z2)

# 使用 out 参数进行元素乘法
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print("z3:", z3)


t1: tensor([[ 0.4481, -1.2375, -1.5883,  0.4481, -1.2375, -1.5883,  0.4481, -1.2375,
         -1.5883],
        [ 0.1689,  1.2353, -0.8415,  0.1689,  1.2353, -0.8415,  0.1689,  1.2353,
         -0.8415]])
y1: tensor([[ 4.2547, -0.1164],
        [-0.1164,  2.2627]])
y2: tensor([[ 4.2547, -0.1164],
        [-0.1164,  2.2627]])
y3: tensor([[ 4.2547, -0.1164],
        [-0.1164,  2.2627]])
z1: tensor([[0.2008, 1.5313, 2.5225],
        [0.0285, 1.5260, 0.7081]])
z2: tensor([[0.2008, 1.5313, 2.5225],
        [0.0285, 1.5260, 0.7081]])
z3: tensor([[0.2008, 1.5313, 2.5225],
        [0.0285, 1.5260, 0.7081]])


In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))

-1.8148311376571655 <class 'float'>


In [12]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[ 0.4481, -1.2375, -1.5883],
        [ 0.1689,  1.2353, -0.8415]])
tensor([[5.4481, 3.7625, 3.4117],
        [5.1689, 6.2353, 4.1585]])
